---
# tasks file for configure-system 
- name: Update all yum packages
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Ensure the firewalld service is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Permit traffic for traefik dashboard
  firewalld: 
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
    zone: public 
  
- name: Permit traffic for portianer
  firewalld: 
    port: "9000/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  
- name: Permit traffic for http
  firewalld: 
    port: "80/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Permit traffic for https
  firewalld: 
    port: "443/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Reload firewalld to apply changes
  command: firewall-cmd --reload