---
# tasks file for configure-system
- name: Update all yum packages
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Ensure the firewalld service is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Permit traffic for traefik dashboard
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Permit traffic for portianer
  ansible.posix.firewalld:
    port: "9000/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Permit traffic for http
  ansible.posix.firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Permit traffic for https
  ansible.posix.firewalld:
    port: "443/tcp"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public

- name: Reload firewalld to apply changes
  ansible.builtin.service:
    name: firewalld
    state: reloaded
