- name: Create folder to store portainer password
  ansible.builtin.file:
    path: /etc/portainercfg
    state: "directory"

- name: Create tmp Portainer Password
  ansible.builtin.copy:
    dest: /etc/portainercfg/portainer_password
    content: "{{ portainer_password }}"

- name: Create docker volume
  docker_volume:
    name: portainer_data

- name: Create docker network
  docker_network:
    name: traefik_network

- name: Run Portainer Container
  docker_container:
    name: portainer
    image: "{{ portainer_version }}"
    state: started
    restart_policy: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "web, websecure"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ inventory_hostname }}`)"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.tls.certresolver: "production"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
      - "/etc/portainercfg/portainer_password:/tmp/portainer_password"
    networks:
      - name: traefik_network
    command: ["--admin-password-file", "/tmp/portainer_password"]
  tags: deploy
