- name: Create Traefik folder for certs
  ansible.builtin.file:
    path: /etc/traefik/certs
    state: directory

- name: Use Traefik config presets
  ansible.builtin.template:
    src: templates/traefik.yml.j2
    dest: /etc/traefik/traefik.yml

- name: Run Traefik Container
  docker_container:
    name: traefik
    image: "{{ traefik_image }}"
    state: started
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      traefik.enable: "true"
      traefik.http.routers.dashboard.entrypoints: "web, websecure"
      traefik.http.routers.dashboard.tls: "true"
      traefik.http.routers.dashboard.tls.certresolver: "production"
      traefik.http.routers.dashboard.rule: "Host(`traefik.{{ inventory_hostname }}`)"
      traefik.http.routers.dashboard.service: "api@internal"
      traefik.http.routers.dashboard.middlewares: "auth"
      traefik.http.middlewares.auth.basicauth.users: "{{ traefik_username }}:{{ traefik_password | b64encode }}"
    volumes:
      - "/etc/traefik:/etc/traefik"
      - "traefik-ssl-certs:/ssl-certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: traefik_network
  tags: deploy_traefik
