---
# tasks file for install-configure-portainer
- name: Install Docker
  import_tasks: install-docker.yml

- name: Deploy Portainer
  import_tasks: deploy-portainer.yml

- name: Deploy Traefik
  import_tasks: deploy-traefik.yml

- name: Deploy Watchtower
  import_tasks: deploy-watchtower.yml
  when:
    - deploy_watchtower is true

- name: Deploy Pocketbase
  import_tasks: deploy-pocketbase.yml
  when:
    - deploy_pocketbase is true
