---
# tasks file for install-configure-portainer
- name: Install docker
  import_tasks: install-docker.yml

- name: Deploy Portainer
  import_tasks: deploy-portainer.yml

- name: Deploy Traefik
  import_tasks: deploy-traefik.yml

- name: Deploy Watchtower
  import_tasks: deploy-watchtower.yml
  when:
    - deploy_watchtower is true

- name: Deploy Dummy App
  import_tasks: deploy-dummy.yml
  when:
    - deploy_dummy is true
