- hosts: all
  become: true
  roles:
    - configure-system
    - install-configure-portainer
  vars:
    traefik_image: traefik:v3.4.0
    traefik_username: matthew
    traefik_password: openshiftisfun
    portainer_version: portainer/portainer-ce:2.27.6
    portainer_password: openshiftisfun
    user_email: <your_email>
    deploy_watchtower: false
    deploy_pocketbase: false
