- hosts: all
  become: true
  roles:
    - configure-system
    - install-configure-portainer
  vars:
    traefik_image: traefik:v3.1
    traefik_username: matthew
    traefik_password: openshiftisfun
    portainer_version: portainer/portainer-ce:2.19.4
    portainer_password: openshiftisfun
    user_email: matthewbnw@gmail.com
    deploy_watchtower: false
    deploy_pocketbase: true
